### ISSUE TITLE
Credits screen over playing game

### ISSUE THREAD

**Issue by davidromani** [BorisBoutillier/Kataster#11]
Select "credits" menu option, then select "menu" and the credits still showing over the main view. Indeed, if you select "play" the credits still showing like in this screen capture.

![Captura de pantalla 2024-09-07 a les 21 09 55](https://github.com/user-attachments/assets/93e47ce3-f1cf-4ae5-81e4-b1b079417ab3)

**Comment by BorisBoutillier** [comment]
Thanks for the feedback.
I have fixed the issue.
