### ISSUE TITLE
break on bevy 0.6

### ISSUE THREAD

**Issue by pyweeker** [BorisBoutillier/Kataster#4]
possible to fix it please , i failed

**Comment by BorisBoutillier** [comment]
You will need to provide more information about the failure.
The v0.6.0 tag the current main head are working with bevy 0.6.0.

Have you tried running one of the simple bevy example from bevy 0.6.0 like 2d/sprite.rs to check that your environment is up to date with requirements for bevy 0.6.0
For example you need to have rust 2021.

At least can you please provide some  error messages.

**Comment by pyweeker** [comment]
it does work now... dont understand what happened.

**Comment by pyweeker** [comment]
Salut, j'essaie de faire une bataille dans un champs d' asteroides, un peu
comme dans les starwars, si j'y arrive pas peux etre fun.je vais plancher
dessus dimanche.
https://github.com/pyweeker/invaders_in_asterofield


je vais m inspirer de ce projet pour faire des gros destroyer avec pleins
de cannons
https://github.com/jonathanrlouie/tanks

Christophe

Le ven. 14 janv. 2022 à 10:36, Boutillier ***@***.***> a
écrit :
