### ISSUE TITLE
sprite sticked on another sprite , with customizable rotation

### ISSUE THREAD

**Issue by pyweeker** [BorisBoutillier/Kataster#5]
Hello Bobox,

is it possible to have a turret sticked on the ship , with rotation mouse driven, to launch spatial torpedoes ?

the way the ship moves made me think about tank movement, on which i tried to add a turret : the turret translate and rotates with the ship , but can become independant if the mouse moves. As i failed , struggling with querystates, children ... just cant get it.

**Comment by BorisBoutillier** [comment]
This game will remain as simple as possible.
