### ISSUE TITLE
Fails To Build

### ISSUE THREAD

**Issue by coruscateor** [BorisBoutillier/Kataster#6]
Hello,

The project fails to build on Windows 10:

```
cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zshare-generics=n --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

This prevents rust-analyzer from working. 

Seems to have something to do with .cargo\config

**Comment by BorisBoutillier** [comment]
Thanks for the catch.
The current code was still requiring the rust 'nightly' version on Windows and Apple.

Fixed with commit (https://github.com/Bobox214/Kataster/commit/76b0af7e03023e9a6050296fe54948cd640975b9)

**Comment by coruscateor** [comment]
It builds! Thanks!
